### ISSUE TITLE
Rustler doesn't compile with Erlang OTP 24

### ISSUE THREAD

**Issue by deepankar-j** [rusterlium/rustler#359]
Issue https://github.com/rusterlium/rustler/issues/357, which was recently resolved prevented compilation of rustler on Erlang OTP 24.   The fix has been merged into master, but the release (v0.22 or perhaps a patch to v0.21?) is needed to make the fix available. 

Due to how rustler is compiled, other libraries (e.g. `:tds_encoding`) can't simply point to the latest master ref to pickup the latest version of rustler (as far as I'm aware).  Hence, a release is needed.

Thanks!

**Comment by filmor** [comment]
You can reference the git version in your nif-crate just fine.

@scrogson Would you be able to do a second RC for 0.22, at least for the Rust crate?

**Comment by scrogson** [comment]
@filmor I don't currently have time to handle this, I've added you as a publisher on hex/crates.

**Comment by filmor** [comment]
I'll try to create a new RC this weekend.

**Comment by filmor** [comment]
I pushed updated `rustler`, `rustler_codegen`, `rustler_mix` and `rustler_sys` packages. Updating the last one of these should be enough to get Rustler working with OTP-24.

**Comment by deepankar-j** [comment]
@filmor :  Thanks for creating the release.  I have a fork of `tds_encoding`, which updates rustler to use `0.22.0-rc.1`.  However, I'm still getting the following error during compilation.

Here's the repo and my change to pickup the latest rustler rc.  Please note that the branch is `update-ruslter`, in case you pull that repo.

https://github.com/MBXSystems/tds-encoding/commit/a19046f36f6432f7610e9877d414daf8f6e035b6

```
error: failed to run custom build command for `rustler_sys v2.0.0`

Caused by:
  process didn't exit successfully: `/Users/dj.jain/git/tds-encoding/_build/dev/lib/tds_encoding/native/tds_encoding/debug/build/rustler_sys-7cca3237334997ef/build-script-build` (exit code: 101)
  --- stdout
  This OTP release uses the unsupported Erlang NIF version "2.16".

  Please report at https://github.com/rustlerium/rustler.

  --- stderr
  thread 'main' panicked at 'gen_api.erl encountered an error.', /Users/dj.jain/.cargo/registry/src/github.com-1ecc6299db9ec823/rustler_sys-2.0.0/build.rs:34:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

== Compilation error in file lib/tds_encoding.ex ==
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    (rustler 0.22.0-rc.1) lib/rustler/compiler.ex:36: Rustler.Compiler.compile_crate/2
    lib/tds_encoding.ex:37: (module)
    (stdlib 3.15) erl_eval.erl:685: :erl_eval.do_apply/6
 ```

**Comment by filmor** [comment]
Well, the important part to update is not in the `mix.exs` but in the `native/tds_encoding/Cargo.toml`, updating the version in there makes the project compile just fine against OTP24 (didn't run it, though).

**Comment by deepankar-j** [comment]
Thank you for pointing me in the right direction, @filmor!  As you can tell, I'm a novice at working with the native interface.

Thanks again!

**Comment by mischov** [comment]
@filmor Do you have any idea when v0.22 might be released as a non-release-candidate?
